export type IncludedSubsection = {
  title: string;
  items: string[];
};

export type IncludedSection = {
  id: string;
  title: string;
  tagline?: string;
  items: string[];
  subsections?: IncludedSubsection[];
};

export const PRICING_EVERYTHING_INCLUDED: IncludedSection[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    tagline: "Everything you need to see, the moment you open Lance.",
    items: [
      "Real-time overview of active projects, pending invoices, unbilled hours, and outstanding proposals",
      "\"Needs you today\" task list — overdue and due-soon items surfaced automatically",
      "Monthly revenue snapshot — collected vs outstanding at a glance",
      "Upcoming client follow-ups displayed on the dashboard",
      "Quick-action buttons to log time, create a project, add a client, or write a note",
      "Global search bar accessible from the dashboard",
    ],
  },
  {
    id: "clients",
    title: "Clients & CRM",
    tagline: "A full client relationship system, not just a contact list.",
    items: [
      "Unlimited clients",
      "Full contact profiles — name, company, email, phone, address, tax ID",
      "Client logo upload",
      "Colour-coded client avatars",
      "Tags for flexible organisation",
      "Internal notes per client",
      "CRM pipeline board — 11-stage Kanban (New Lead → Closed Lost)",
      "Drag-and-drop between pipeline stages",
      "Activity timeline — log calls, emails, meetings, and notes per client",
      "Multiple follow-up tasks per client — title, details, due date, reminder date, mark complete",
      "Lead source tracking",
      "Estimated deal value per client",
      "Client archiving — soft delete that preserves all history",
      "Hard delete — available only when no related records exist",
      "CSV import — bulk create or update clients from a spreadsheet",
      "CSV export — download your full client list",
      "AI-generated client summary",
    ],
  },
  {
    id: "projects",
    title: "Projects",
    tagline: "Projects that stay organised from kickoff to delivery.",
    items: [
      "Unlimited projects",
      "Link projects to clients",
      "Project status — Active, On Hold, Completed, Cancelled",
      "Project budget tracking",
      "Project-level hourly rate (overrides your default)",
      "Start date and due date",
      "Custom emoji + colour icon per project",
      "Kanban board with custom columns — create your own workflow stages",
      "Rename, reorder, and colour-code columns",
      "Mark columns as \"done\" for completion tracking",
      "List view — compact table format with inline editing",
      "Task filters — by status, priority, hide completed",
      "CSV import and export for tasks",
      "Project-level time entry log",
    ],
  },
  {
    id: "tasks",
    title: "Tasks",
    tagline: "Every deliverable, tracked and prioritised.",
    items: [
      "Unlimited tasks per project",
      "Task title and rich text description",
      "Priority levels — Low, Medium, High, Urgent",
      "Due dates",
      "Estimated hours",
      "Link tasks to time entries",
      "Task comments",
      "Duplicate tasks",
      "Quick-add from Kanban column",
      "Create tasks directly from Notes — highlight text, turn it into a task instantly",
      "Bulk import via CSV",
    ],
  },
  {
    id: "time",
    title: "Time Tracking",
    tagline: "Know exactly where your hours go — and bill for all of them.",
    items: [
      "Live timer — start, pause, stop, resume",
      "Timer persists while navigating the app",
      "Timer state saved if browser is closed accidentally",
      "Manual time entry — enter total hours or specify start/end times",
      "Multiple time ranges per entry",
      "Link time entries to projects and tasks",
      "Billable / non-billable toggle per entry",
      "Per-entry hourly rate override",
      "Billing status tracking — Unbilled → Billed → Paid automatically",
      "Weekly timesheet view",
      "Full time log with filters — by date range, project, billable status",
      "Date range filters — This Week, This Month, Last 90 Days, Custom, All Time",
      "Unbilled hours surfaced on dashboard",
      "CSV export of time logs",
      "CSV import for bulk time entry upload",
      "Direct import from time logs into invoices",
    ],
  },
  {
    id: "invoices",
    title: "Invoices",
    tagline: "Professional invoices that get paid faster.",
    items: [
      "Unlimited invoices",
      "Auto-generated invoice numbers",
      "Configurable numbering format — custom prefix, year toggle, padding, starting number, yearly reset",
      "Invoice statuses — Draft, Sent, Reminder sent, Overdue, Paid, Cancelled",
      "Manual line items — description, quantity, unit price, line date",
      "Import billable time entries as line items — one click",
      "Tax presets — create multiple rates, set a default",
      "Discount field",
      "Invoice notes (above line items)",
      "Invoice footer (below line items)",
      "Bank details / payment instructions",
      "Default content templates — pre-fill notes, footer, and bank details on every invoice",
      "Branded invoice PDF — includes your logo, business info, and brand colour",
      "Send invoice by email directly from Lance",
      "Merge tags in email templates — {{client_name}}, {{invoice_number}}, {{due_date}}, {{total}}, etc.",
      "Reminder mode — send follow-up emails for unpaid invoices",
      "Receipt mode — send payment confirmation emails",
      "Automatic payment reminders — configure days before due date, custom subject and message",
      "Mark as Paid — records payment date",
      "Edit lock — sent/paid invoices are read-only until unlocked",
      "Duplicate invoices",
      "Download PDF",
      "Invoice preview before sending",
      "CSV import and export",
      "Audit trail — time entries linked to the invoice they were billed on",
      "Deep link from approval requests to create a pre-filled invoice",
    ],
  },
  {
    id: "services",
    title: "Services",
    tagline: "Your pricing menu, ready to use in every proposal and contract.",
    items: [
      "Unlimited services in your catalogue",
      "Service name and description",
      "Default price per service",
      "Recurring toggle — Monthly or Annual billing",
      "Default task checklist per service — auto-populates project tasks when used in a proposal",
      "Use services in proposals and contracts",
      "Edit services without affecting existing proposals or contracts (snapshot system)",
    ],
  },
  {
    id: "proposals",
    title: "Proposals",
    tagline: "Proposals that look as good as your work.",
    items: [
      "Unlimited proposals",
      "Auto-generated proposal identifier — P-YYYY-#####",
      "Cover image — upload per proposal or set a default",
      "Brand colour per proposal",
      "Objective and presentation text — rich text editor",
      "Add services from your catalogue or create custom line items inline",
      "Drag-and-drop service reorder",
      "Subtotal auto-calculated",
      "Timeline and availability fields",
      "Validity period — configurable default, minimum 1 day, expiry auto-calculated",
      "Payment structure — Upfront or Installments",
      "Installment description",
      "Payment methods — Bank Transfer, Credit Card, Debit Card, PayPal, Stripe, Crypto, Other",
      "Discount — amount or percentage",
      "Terms and conditions — rich text, pre-fills from settings default",
      "Client snapshot — client details frozen at time of sending for historical accuracy",
      "Public proposal link — no client login required",
      "Read tracking — notified when client opens the proposal",
      "One-click client acceptance",
      "Status tracking — Draft, Sent, Read, Accepted, Archived",
      "Convert accepted proposal to contract in one click",
      "Duplicate proposals",
      "Proposal settings — configure defaults for cover image, colour, validity, payment structure, payment methods, and conditions",
      "Acceptance rate stats",
    ],
  },
  {
    id: "contracts",
    title: "Contracts",
    tagline: "Legally signed contracts without the back-and-forth.",
    items: [
      "Unlimited contracts",
      "Auto-generated contract identifier — C-YYYY-#####",
      "Import from accepted proposal — client info and services carry over automatically",
      "Or start from scratch",
      "Freelancer and client party information — name, email, phone, address, entity type",
      "Party details pre-fill from your settings and client record",
      "Services section with drag-and-drop reorder",
      "Timeline, payment terms, and additional clause fields",
      "Discount — amount or percentage",
      "Reusable contract templates — HTML-based with variable placeholders",
      "Variable placeholders — {{freelancer_name}}, {{client_name}}, {{services_list}}, {{total_amount}}, {{timeline}}, {{payment_terms}}, and more",
      "Multiple templates — set any as default",
      "Dual e-signature flow — you sign first, then send to client",
      "Client OTP signing — client receives a 6-digit code by email, verifies identity, and signs",
      "OTP expires after 15 minutes",
      "Client can update their own details before signing",
      "Contract lock — core fields become immutable after sending (database-enforced)",
      "Status tracking — Draft, Pending Signatures, Signed, Cancelled",
      "Cancellation with reason — preserved for records",
      "Download signed contract as PDF",
      "Notifications for every signature event",
      "Client snapshot for historical accuracy",
    ],
  },
  {
    id: "approvals",
    title: "Approvals",
    tagline: "Client sign-off without the email chain.",
    items: [
      "Unlimited approval requests",
      "Upload any file type — images, PDFs, videos, documents",
      "Multiple files per request",
      "Pinned comments — clients click directly on an image to leave a comment at that exact location",
      "Client access — no account required, token-based link",
      "Client identity via name + email on first visit (saved in browser)",
      "Approve or reject with confirmation",
      "Comment editing and deletion by the original commenter",
      "Version tracking — update the version number between revision rounds",
      "Folder organisation — create folders with name, emoji, and colour",
      "Filter by status — Pending, Approved, Rejected, Commented",
      "Filter by client, project, or folder",
      "Due dates per request",
      "Multiple email recipients per request",
      "Client file upload — clients can upload reference files or source assets",
      "Real-time notifications — approved, rejected, commented",
      "Create invoice directly from an approved request — client and project pre-filled",
      "200 MB total file storage",
    ],
  },
  {
    id: "portal",
    title: "Client Portal",
    tagline: "Give clients self-service access. Stop resending files.",
    items: [
      "Unique private portal URL per client",
      "Token-based access — no client account required",
      "Enable or disable per client at any time",
      "Choose which sections are visible per client:",
      "Details — their contact information",
      "Invoices — all invoices with PDF download",
      "Proposals — sent proposals, can still accept from portal",
      "Contracts — can sign pending contracts from portal",
      "Approvals — can review, comment, approve, or reject",
      "Time — optional, show billable, non-billable, or both",
      "Send portal link by email directly from Lance",
      "Copy portal URL to share manually",
      "Portal access revoked instantly when disabled",
      "Client data fully isolated — clients can only see their own records",
    ],
  },
  {
    id: "notes",
    title: "Notes",
    tagline: "One place for briefs, meeting notes, and ideas.",
    items: [
      "Unlimited notes",
      "Rich text editor — bold, italic, underline, headings, lists, links, blockquotes, dividers",
      "Inline image uploads",
      "Turn highlighted text into a task — select any text, assign to a project",
      "Link notes to clients and projects",
      "Tags — comma-separated, filterable",
      "Emoji icon per note",
      "Cover colour — 8 presets",
      "Folder organisation — name, emoji, colour",
      "Auto-save — 800ms after stopping",
      "Download as .doc file (Word-compatible)",
      "Global search includes note titles and content",
      "Deep link to specific notes",
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    tagline: "Stay on top of everything without checking everything.",
    items: [
      "In-app notification feed with unread badge count",
      "Real-time updates via live channel",
      "Email notifications — toggleable per category",
      "Notification categories — invoices, approvals, proposals, contracts, projects, tasks, system",
      "Due soon alerts — configurable days before due date (default 7 days, 3 days for contracts)",
      "Overdue alerts",
      "Trial expiry reminders — 5 days, 1 day, day-of",
      "Event deduplication — no duplicate notifications",
      "Bulk mark all as read",
      "Bulk delete all",
      "Per-notification delete",
      "Marketing email preference — opt in/out of product updates and tips",
    ],
  },
  {
    id: "search",
    title: "Search",
    tagline: "Find anything, instantly.",
    items: [
      "Global search across Projects, Clients, Invoices, Tasks, Notes, Time Entries, and Approvals",
      "Partial-match, case-insensitive search",
      "Results grouped by category",
      "Up to 10 results per category",
      "Direct navigation from search result to item",
    ],
  },
  {
    id: "settings",
    title: "Settings & Customisation",
    tagline: "Set it up once. Works your way from day one.",
    items: [],
    subsections: [
      {
        title: "Profile",
        items: [
          "First name, last name, email, phone",
          "Profile photo upload (max 500 KB)",
          "Account deletion",
        ],
      },
      {
        title: "Company",
        items: [
          "Business name, email, phone, website",
          "Full business address",
          "Tax ID",
          "Business logo upload (max 1 MB)",
          "Secondary email logo for dark backgrounds",
          "Light/Dark logo variant for emails",
          "Brand colour for client emails — applied to headers and buttons",
          "Custom email footer HTML",
          "Standard or custom footer toggle",
        ],
      },
      {
        title: "Locale",
        items: [
          "Auto-detect from browser in one click",
          "Default currency — 150+ currencies supported",
          "Currency display format — Symbol, Code, or Name",
          "Date format — DD/MM/YYYY, MM/DD/YYYY, YYYY-MM-DD, and regional variants",
          "Number format — US, European, French, Swiss styles",
          "Time format — 12-hour or 24-hour",
          "Timezone — all world timezones, affects notification timing and due dates",
        ],
      },
      {
        title: "Invoices",
        items: [
          "Default hourly rate",
          "Invoice number prefix",
          "Year inclusion toggle",
          "Number padding — 1 to 6 digits",
          "Starting number — useful when migrating from another tool",
          "Yearly reset toggle",
          "Default invoice notes",
          "Default invoice footer",
          "Default bank details",
          "Default email subject template",
          "Default email message template with merge tags",
          "Automatic payment reminder toggle",
          "Reminder timing — days before due date",
          "Reminder email subject and body templates",
          "Tax preset management — multiple rates, set default",
        ],
      },
      {
        title: "Proposals",
        items: [
          "Default cover image (max 10 MB, 1500×500 px recommended)",
          "Default brand colour",
          "Default validity period",
          "Immediate availability toggle and text",
          "Default payment structure",
          "Default installment description",
          "Default accepted payment methods",
          "Default terms and conditions",
        ],
      },
      {
        title: "Notifications",
        items: [
          "Per-category email toggle",
          "In-app notifications always on",
        ],
      },
      {
        title: "Storage",
        items: [
          "200 MB total per account",
          "Usage breakdown by file type",
          "Delete individual files to free space",
          "Visual usage bar with colour-coded alerts",
        ],
      },
      {
        title: "Subscription",
        items: [
          "Monthly or annual plan",
          "Manage via Stripe Customer Portal",
          "Update payment method",
          "View billing history",
          "Cancel, pause, or reactivate",
        ],
      },
    ],
  },
  {
    id: "sharing",
    title: "Sharing & Access",
    tagline: "Built for how freelancers actually work with clients.",
    items: [
      "Public proposal pages — no client login",
      "Public contract signing pages — OTP verified",
      "Public approval pages — no client login",
      "Client portal — no client login",
      "All public links are token-based and unique",
      "Links can be revoked or disabled at any time",
    ],
  },
  {
    id: "import-export",
    title: "Import & Export",
    tagline: "Your data, always portable.",
    items: [
      "CSV import — Clients, Time Entries, Tasks (per project)",
      "CSV export — Clients, Invoices, Time Entries",
      "Client import uses email as unique key — updates existing records on match",
      "Invoice import template available",
      "Note download as .doc",
    ],
  },
];
