export type ContractStatus = "draft" | "pending_signatures" | "signed" | "cancelled";

export type Contract = {
  id: string;
  user_id: string;
  client_id: string | null;
  project_id: string | null;
  proposal_id: string | null;
  template_id: string | null;
  identifier: string;
  status: ContractStatus;
  client_name: string | null;
  client_company: string | null;
  client_email: string | null;
  client_phone: string | null;
  client_address: string | null;
  client_city: string | null;
  client_state: string | null;
  client_zip: string | null;
  client_country: string | null;
  client_tax_id: string | null;
  client_company_name: string | null;
  client_company_registration: string | null;
  client_complement: string | null;
  client_street: string | null;
  client_street2: string | null;
  client_entity_type: "individual" | "company";
  freelancer_name: string | null;
  freelancer_company: string | null;
  freelancer_email: string | null;
  freelancer_phone: string | null;
  freelancer_address: string | null;
  freelancer_city: string | null;
  freelancer_state: string | null;
  freelancer_zip: string | null;
  freelancer_country: string | null;
  freelancer_tax_id: string | null;
  freelancer_company_name: string | null;
  freelancer_company_registration: string | null;
  freelancer_complement: string | null;
  freelancer_street: string | null;
  freelancer_street2: string | null;
  timeline_days: number | null;
  reminder_near_end: boolean;
  immediate_availability: boolean;
  payment_structure: "upfront" | "installments" | null;
  installment_description: string | null;
  payment_methods: string[];
  payment_link: string | null;
  additional_clause: string | null;
  subtotal: number;
  discount: number | null;
  discount_type: "percent" | "fixed" | null;
  total: number;
  public_token: string;
  sent_at: string | null;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  freelancer_signed_at: string | null;
  freelancer_signed_name: string | null;
  freelancer_sign_ip: string | null;
  freelancer_sign_geo: string | null;
  freelancer_sign_device: string | null;
  freelancer_sign_isp: string | null;
  freelancer_sign_email_verified: boolean;
  client_signed_at: string | null;
  client_signed_name: string | null;
  client_sign_ip: string | null;
  client_sign_geo: string | null;
  client_sign_device: string | null;
  client_sign_isp: string | null;
  client_sign_email_verified: boolean;
  created_at: string;
  updated_at: string;
};

export type ContractService = {
  id: string;
  contract_id: string;
  service_id: string | null;
  name: string;
  description: string | null;
  price: number | null;
  quantity: number;
  sort_order: number;
};
