// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

/** Prefer JWT anon key when both legacy JWT and `sb_publishable_*` keys are configured. */
function pickSupabaseApiKey(): string {
  const anon = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();
  const publishable = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
  if (anon?.startsWith('eyJ')) return anon;
  if (publishable?.startsWith('eyJ')) return publishable;
  return anon || publishable || '';
}

export const supabaseAnonKey = pickSupabaseApiKey();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});